export * from './home/HomeScreen';
export * from './about/AboutScreen';
export * from './courses/CourseListScreen';
export * from './courses/CourseDetailsScreen';
export * from './gallery/GalleryScreen';
export * from './testimonials/TestimonialScreen';
export * from './faq/FAQScreen';
export * from './contact/ContactScreen';
export * from './registration/RegistrationScreen';
